services:
  mqtt:
    image: rrojano/mqtt
    container_name: broker-mqtt
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt/mqtt.conf:/mosquitto/config/mosquitto.conf
    restart: unless-stopped

  casino:
    build:
      context: .
    container_name: casino
    depends_on:
      - mqtt
    ports:
      - "3000:3000"
    working_dir: /app/backend
    command: node casino.js

  ruleta:
    build:
      context: .
    container_name: ruleta
    depends_on:
      - mqtt
    working_dir: /app/backend
    command: node ruleta.js
